---
name: Config-Trivial-Storable
version: 0.10
author:
  - 'Adam Trickett, E<lt>atrickett@cpan.orgE<gt>'
abstract: Very simple tool for reading and writing very simple configuration files
license: gpl
requires:
  perl: 5.6.1
provides:
  Config::Trivial::Storable:
    file: lib/Config/Trivial/Storable.pm
    version: 0.10
