---
name: Config-Trivial-Storable
version: 0.30
author:
  - 'Adam Trickett, E<lt>atrickett@cpan.orgE<gt>'
abstract: Very simple tool for reading and writing very simple Storable configuration files
license: gpl
distribution_type: module
requires:
  Config::Trivial: 0.60
  Storable: 2.0
  perl: 5.6.1
provides:
  Config::Trivial::Storable:
    file: lib/Config/Trivial/Storable.pm
    version: 0.30
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
