---
name: Config-Trivial-Storable
version: 0.20
author:
  - 'Adam Trickett, E<lt>atrickett@cpan.orgE<gt>'
abstract: Very simple tool for reading and writing very simple Storable configuration files
license: gpl
requires:
  Config::Trivial: 0.51
  Storable: 2.0
  perl: 5.6.1
provides:
  Config::Trivial::Storable:
    file: lib/Config/Trivial/Storable.pm
    version: 0.20
generated_by: Module::Build version 0.2611
